In [1]:
import pandas as pd

In [2]:
data = [['soham', 89], ['reet', 87], ['geet', 78], ['ganu', 88]]

In [3]:
data

[['soham', 89], ['reet', 87], ['geet', 78], ['ganu', 88]]

In [8]:
pd.DataFrame(data, columns=["Name", "Marks"], index = [1, 2, 3, 4])

    Name  Marks
1  soham     89
2   reet     87
3   geet     78
4   ganu     88

In [9]:
data = {"a": [43, 45, 76], "b": [29, 57, 33]}

In [10]:
data

{'a': [43, 45, 76], 'b': [29, 57, 33]}

In [12]:
df = pd.DataFrame(data)

In [13]:
df

    a   b
0  43  29
1  45  57
2  76  33

In [14]:
import numpy as np

In [15]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

In [20]:
df = pd.DataFrame(arr, columns=["A", "B"])

In [21]:
df

   A  B
0  1  2
1  3  4
2  5  6

In [22]:
df = pd.read_csv("students.csv")

In [23]:
df

    roll_no     name  marks
0         1    Aarav     85
1         2   Vihaan     78
2         3   Aditya     92
3         4  Krishna     88
4         5    Arjun     74
5         6      Sai     81
6         7   Ishaan     69
7         8    Rohan     95
8         9    Kabir     87
9        10     Yash     72
10       11      Dev     90
11       12       Om     76
12       13    Rudra     84
13       14    Kunal     79
14       15    Harsh     68
15       16     Aman     91
16       17   Neeraj     73
17       18    Manav     86
18       19   Tanmay     77
19       20      Raj     89

In [24]:
df = pd.read_json("students.json")

In [25]:
df

    roll_no     name  marks
0         1    Aarav     85
1         2   Vihaan     78
2         3   Aditya     92
3         4  Krishna     88
4         5    Arjun     74
5         6      Sai     81
6         7   Ishaan     69
7         8    Rohan     95
8         9    Kabir     87
9        10     Yash     72
10       11      Dev     90
11       12       Om     76
12       13    Rudra     84
13       14    Kunal     79
14       15    Harsh     68
15       16     Aman     91
16       17   Neeraj     73
17       18    Manav     86
18       19   Tanmay     77
19       20      Raj     89