In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("Data.csv")

In [5]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [10]:
type(df['Actor'])

pandas.core.series.Series

In [11]:
df[['Actor', 'IMDb']]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [17]:
df.loc[4] #By label (index)

Actor                   Ranveer Singh
Film                        Padmaavat
Year                             2018
Genre                      Historical
BoxOffice(INR Crore)              585
IMDb                              7.0
Name: 4, dtype: object

In [18]:
df.iloc[4] #By position

Actor                   Ranveer Singh
Film                        Padmaavat
Year                             2018
Genre                      Historical
BoxOffice(INR Crore)              585
IMDb                              7.0
Name: 4, dtype: object

In [19]:
df.loc[5, 'Film']

'Andhadhun'

In [24]:
df.loc[3:7, ['Actor', 'Film', 'BoxOffice(INR Crore)']] #3:7 7 is inclusive

                Actor        Film  BoxOffice(INR Crore)
3       Ranbir Kapoor  Brahmastra                   431
4       Ranveer Singh   Padmaavat                   585
5  Ayushmann Khurrana   Andhadhun                   111
6       Rajkummar Rao       Stree                   180
7      Hrithik Roshan         War                   475

In [28]:
df.iloc[3:7, 0:4] #3:7, 0:4 7 & 4 is EXclusive

                Actor        Film  Year          Genre
3       Ranbir Kapoor  Brahmastra  2022        Fantasy
4       Ranveer Singh   Padmaavat  2018     Historical
5  Ayushmann Khurrana   Andhadhun  2018       Thriller
6       Rajkummar Rao       Stree  2018  Horror Comedy

In [33]:
df.at[7, 'Actor']

'Hrithik Roshan'

In [34]:
df.iat[7, 0]

'Hrithik Roshan'

### Filtering

In [35]:
df[df['IMDb']> 6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [37]:
df[df['IMDb']> 7]['Film']

0                      Pathaan
2                       Dangal
5                    Andhadhun
6                        Stree
11    Uri: The Surgical Strike
Name: Film, dtype: object

In [45]:
df[(df['IMDb']> 6) & (df['Year']==2019)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [46]:
df.query("Year == 2019 and IMDb > 7")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2