In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df.sort_values("Year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [7]:
df.sort_values("Year", ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [28]:
df2 = df.sort_values(["Year", "IMDb"])

In [29]:
df2.reset_index(drop=True, inplace=True) #inplace true use to save changes in main dataset

In [30]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [40]:
df2["Rank"] = df2["IMDb"].rank(ascending=False, method="dense")

In [43]:
df2.reset_index(drop=True, inplace=True)

In [44]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Hrithik Roshan,War,2019,Action,475,6.5,7.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [48]:
df2 = df2[["Rank", "Film", "Year", "Genre", "IMDb", "BoxOffice(INR Crore)", "Actor"]]   # Reorder as desired

In [49]:
df2.sort_values("Rank")

,Rank,Film,Year,Genre,IMDb,BoxOffice(INR Crore),Actor
0,1.0,Dangal,2016,Biography,8.4,2024,Aamir Khan
5,2.0,Andhadhun,2018,Thriller,8.3,111,Ayushmann Khurrana
8,3.0,Uri: The Surgical Strike,2019,Action,8.2,342,Vicky Kaushal
4,4.0,Stree,2018,Horror Comedy,7.5,180,Rajkummar Rao
11,5.0,Pathaan,2023,Action,7.2,1050,Shah Rukh Khan
3,6.0,Padmaavat,2018,Historical,7.0,585,Ranveer Singh
7,6.0,Good Newwz,2019,Comedy,7.0,318,Akshay Kumar
6,7.0,War,2019,Action,6.5,475,Hrithik Roshan
2,8.0,Badrinath Ki Dulhania,2017,Romantic Comedy,6.1,201,Varun Dhawan
1,9.0,Tiger Zinda Hai,2017,Action,6.0,565,Salman Khan
10,10.0,Bhool Bhulaiyaa 2,2022,Horror Comedy,5.9,266,Kartik Aaryan
9,11.0,Brahmastra,2022,Fantasy,5.6,431,Ranbir Kapoor

In [50]:
df2.reset_index(drop=True, inplace=True)

In [51]:
df2

,Rank,Film,Year,Genre,IMDb,BoxOffice(INR Crore),Actor
0,1.0,Dangal,2016,Biography,8.4,2024,Aamir Khan
1,9.0,Tiger Zinda Hai,2017,Action,6.0,565,Salman Khan
2,8.0,Badrinath Ki Dulhania,2017,Romantic Comedy,6.1,201,Varun Dhawan
3,6.0,Padmaavat,2018,Historical,7.0,585,Ranveer Singh
4,4.0,Stree,2018,Horror Comedy,7.5,180,Rajkummar Rao
5,2.0,Andhadhun,2018,Thriller,8.3,111,Ayushmann Khurrana
6,7.0,War,2019,Action,6.5,475,Hrithik Roshan
7,6.0,Good Newwz,2019,Comedy,7.0,318,Akshay Kumar
8,3.0,Uri: The Surgical Strike,2019,Action,8.2,342,Vicky Kaushal
9,11.0,Brahmastra,2022,Fantasy,5.6,431,Ranbir Kapoor
10,10.0,Bhool Bhulaiyaa 2,2022,Horror Comedy,5.9,266,Kartik Aaryan
11,5.0,Pathaan,2023,Action,7.2,1050,Shah Rukh Khan