In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data_cleaning.csv")

In [3]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

### Fill null values

In [31]:
df.isnull() #function shows the true wherever the data contains null value

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [8]:
df.isnull().sum() #Function use to show the no. of null values as per columns

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [10]:
df.dropna() #Function use to drop the rows that contain any null value

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [11]:
df.dropna(axis=1) #Function use to drop the columns that contain any null value

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [12]:
df.fillna(0) #Function use to fill null value with 0

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [14]:
df["Age"].fillna(df["Age"].mean()) #Function use to fill null values with mean

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [21]:
df.ffill() #Function use to fill the null values with previous index value

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [22]:
df.bfill() #Function use to fill the null values with next index value

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

### Remove Duplicate Values

In [28]:
df.duplicated() #Function use to find the duplicate rows

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [29]:
df.drop_duplicates() #Function use to remove duplicate rows

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [30]:
df.duplicated(subset = ["Name", "Age"]) #Function use to find duplicate values of particular columns

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

### String Methods

In [34]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [35]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [36]:
df["City"].str.contains("delhi", case = False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [37]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      object
 1   Age        6 non-null      float64
 2   City       9 non-null      object
 3   Gender     9 non-null      object
 4   Email      9 non-null      object
 5   Join Date  8 non-null      object
dtypes: float64(1), object(5)
memory usage: 564.0+ bytes

In [39]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [52]:
df2 = df.dropna().copy()

In [53]:
df2["Age"] = df2["Age"].astype(int)

In [54]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [55]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      int64
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
dtypes: int64(1), object(5)
memory usage: 280.0+ bytes

In [58]:
df2["Age Group"] = df2["Age"].apply(lambda x: "Adult" if x >= 25 else "Minor")

In [59]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai      M  david@example.com  12-11-2019     Minor
6  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
7  Alice   25     New York      F  alice@example.com  01-05-2021     Adult

In [60]:
gender_map = {"M": "Male", "F": "Female"}
df2["Gender"] = df2["Gender"].map(gender_map)

In [61]:
df2

    Name  Age         City  Gender              Email   Join Date Age Group
0  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai    Male  david@example.com  12-11-2019     Minor
6  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
7  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult

In [67]:
df2["City"] = df2["City"].replace({"Delhi": "New Delhi", "Mumbai": "New Mumbai"})

In [68]:
df2

    Name  Age         City  Gender              Email   Join Date Age Group
0  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4  David   22   New Mumbai    Male  david@example.com  12-11-2019     Minor
6  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
7  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult