In [1]:
import pandas as pd

In [7]:
Data = {
    'Name': ['Geet', 'Reet', 'Meet', 'sid', 'rid'],
    'Math': [78, 93, 86, 79, 82],
    'Science': [89, 74, 96, 83, 74],
    'English': [79, 85, 93, 74, 84]
}
df = pd.DataFrame(Data)

In [8]:
df

   Name  Math  Science  English
0  Geet    78       89       79
1  Reet    93       74       85
2  Meet    86       96       93
3   sid    79       83       74
4   rid    82       74       84

In [16]:
melt_df = df.melt(id_vars=["Name"], value_vars=["Math", "Science", "English"], var_name="Subject", value_name="Score")

In [17]:
melt_df

    Name  Subject  Score
0   Geet     Math     78
1   Reet     Math     93
2   Meet     Math     86
3    sid     Math     79
4    rid     Math     82
5   Geet  Science     89
6   Reet  Science     74
7   Meet  Science     96
8    sid  Science     83
9    rid  Science     74
10  Geet  English     79
11  Reet  English     85
12  Meet  English     93
13   sid  English     74
14   rid  English     84

In [19]:
df.pivot = melt_df.pivot(
    index="Name",
    columns="Subject",
    values="Score")

In [20]:
df.pivot

Subject  English  Math  Science
Name
Geet          79    78       89
Meet          93    86       96
Reet          85    93       74
rid           84    82       74
sid           74    79       83