In [2]:
import pandas as pd

In [6]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

In [7]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [10]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [15]:
pd.merge(employees, departments, on="DeptID") #inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [16]:
pd.merge(employees, departments, on="DeptID", how="left") #left join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [17]:
pd.merge(employees, departments, on="DeptID", how="right") #right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [18]:
pd.merge(employees, departments, on="DeptID", how="outer") #outer join

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [23]:
df1 = pd.DataFrame({"Name": ["Geet", "Reet"], "Score": [93, 87]})
df2 = pd.DataFrame({"Name": ["Samay", "Amey"], "Age": [23, 21]})

In [24]:
df1

   Name  Score
0  Geet     93
1  Reet     87

In [25]:
df2

    Name  Age
0  Samay   23
1   Amey   21

In [26]:
pd.concat([df1, df2])

    Name  Score   Age
0   Geet   93.0   NaN
1   Reet   87.0   NaN
0  Samay    NaN  23.0
1   Amey    NaN  21.0

In [27]:
pd.concat([df1, df2], axis=1)

   Name  Score   Name  Age
0  Geet     93  Samay   23
1  Reet     87   Amey   21